apiVersion: v1
kind: Service
metadata:
  name: gwa
  labels:
    app: gwa
spec:
  type: NodePort
  selector:
    app: gwa  # must match the pod label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080