name: Build and Deploy with Helm

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'helm/**'
      - 'README.md'

env:
  HELM_RELEASE_NAME: gwa
  K8S_NAMESPACE: default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate unique tag
        id: tag
        run: |
          echo "TAG=${GITHUB_SHA::7}-$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_IMAGE }}:latest
            ${{ secrets.DOCKER_IMAGE }}:${{ steps.tag.outputs.TAG }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate unique tag
        id: tag
        run: |
          echo "TAG=${GITHUB_SHA::7}-$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Setup Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: kind-cluster

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./helm/gwa-chart \
            --namespace ${{ env.K8S_NAMESPACE }} \
            --create-namespace \
            --set image.tag=${{ steps.tag.outputs.TAG }} \
            --set image.repository=${{ secrets.DOCKER_IMAGE }} \
            --wait

  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate unique tag
        id: tag
        run: |
          echo "TAG=${GITHUB_SHA::7}-$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Setup Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: kind-cluster

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./helm/gwa-chart \
            --namespace ${{ env.K8S_NAMESPACE }} \
            --create-namespace \
            --set image.tag=${{ steps.tag.outputs.TAG }} \
            --set image.repository=${{ secrets.DOCKER_IMAGE }} \
            --wait

      - name: Wait for deployment
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 10  # Give some time for pods to start
          kubectl wait --for=condition=available --timeout=300s deployment/${{ env.HELM_RELEASE_NAME }} -n ${{ env.K8S_NAMESPACE }}

      - name: Monitor rolling update
        run: |
          echo "Current pods before update:"
          kubectl get pods -n ${{ env.K8S_NAMESPACE }} -l app=gwa
          
          echo "\nWatching deployment rollout..."
          kubectl rollout status deployment/${{ env.HELM_RELEASE_NAME }} -n ${{ env.K8S_NAMESPACE }}
          
          echo "\nPod status after update:"
          kubectl get pods -n ${{ env.K8S_NAMESPACE }} -l app=gwa
          
          echo "\nDeployment details:"
          kubectl describe deployment ${{ env.HELM_RELEASE_NAME }} -n ${{ env.K8S_NAMESPACE }}
          
          echo "\nRollout history:"
          kubectl rollout history deployment/${{ env.HELM_RELEASE_NAME }} -n ${{ env.K8S_NAMESPACE }}

      - name: Test deployment
        run: |
          # Wait for service to be available
          echo "Waiting for service..."
          kubectl get svc ${{ env.HELM_RELEASE_NAME }} -n ${{ env.K8S_NAMESPACE }}
          
          NODE_PORT=$(kubectl get svc ${{ env.HELM_RELEASE_NAME }} -n ${{ env.K8S_NAMESPACE }} -o jsonpath='{.spec.ports[0].nodePort}')
          echo "Service exposed on port: $NODE_PORT"
          
          # Wait for pods to be ready
          echo "Waiting for pods..."
          sleep 30
          
          # Check pods with your deployment labels
          READY_PODS=$(kubectl get pods -n ${{ env.K8S_NAMESPACE }} -l app=gwa -o jsonpath='{.items[*].status.containerStatuses[0].ready}' | tr ' ' '\n' | grep -c "true")
          TOTAL_PODS=$(kubectl get pods -n ${{ env.K8S_NAMESPACE }} -l app=gwa --no-headers | wc -l)
          
          echo "Ready Pods: $READY_PODS"
          echo "Total Pods: $TOTAL_PODS"
          
          if [ "$READY_PODS" -ne "$TOTAL_PODS" ]; then
            echo "Not all pods are ready! Ready: $READY_PODS, Total: $TOTAL_PODS"
            kubectl describe pods -n ${{ env.K8S_NAMESPACE }} -l app=gwa
            exit 1
          fi



  # Update Helm Chart
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/gwa-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "ifeoluwa1201@gmail.com"
          git config --global user.name "IfeOlaitan"
          git add helm/gwa/values.yaml
          git commit -m "Update tag in Helm chart"
          git push

  rollback:
    needs: test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate unique tag
        id: tag
        run: |
          echo "TAG=${GITHUB_SHA::7}-$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Setup Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: kind-cluster

      - name: Deploy and then Rollback
        run: |
          # First deploy the current version
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./helm/gwa-chart \
            --namespace ${{ env.K8S_NAMESPACE }} \
            --create-namespace \
            --set image.tag=${{ steps.tag.outputs.TAG }} \
            --set image.repository=${{ secrets.DOCKER_IMAGE }} \
            --wait

          echo "Deployment failed! Rolling back..."
          helm rollback ${{ env.HELM_RELEASE_NAME }} 0 -n ${{ env.K8S_NAMESPACE }}
          
          echo "\nWaiting for rollback to complete..."
          kubectl rollout status deployment/${{ env.HELM_RELEASE_NAME }} -n ${{ env.K8S_NAMESPACE }}
          
          echo "\nPod status after rollback:"
          kubectl get pods -n ${{ env.K8S_NAMESPACE }} -l app=gwa

  cleanup:
    needs: [build, deploy, test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: kind-cluster

      - name: Cleanup resources
        run: |
          echo "Cleaning up resources..."
          helm list -n ${{ env.K8S_NAMESPACE }}
          kubectl get all -n ${{ env.K8S_NAMESPACE }}